name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # light tooling (optional)
          pip install ruff pytest

      - name: Lint (ruff)
        run: ruff check .

      # If you don’t have tests yet, this stays green.
      - name: Run tests
        run: pytest -q || true

      # Smoke run your full pipeline to catch breaking changes
      - name: Smoke run pipeline
        run: python script/run_all.py

      # Publish key outputs so reviewers can download them
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-outputs
          path: |
            data/**/*.csv
            refined_policies/**/*
