name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff pytest

      # Make lint non-blocking for now
      - name: Lint (ruff)
        run: ruff check . || true

      # If you don’t have tests, keep this non-blocking as well
      - name: Run tests
        run: pytest -q || true

      - name: Smoke run pipeline
        run: python script/run_all.py || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-outputs
          path: |
            data/**/*.csv
            refined_policies/**/*
